name: 'Check out many'
description: 'Check out all the repos'
inputs:
  repos:
    description: 'A list of repositories to check out separated by a new line'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.repos }}.
      shell: bash
