name: 'Check out many'
description: 'Check out all the repos'
inputs:
  repos:
    description: 'A list of repositories to check out separated by a new line'
    required: true
  token:
    description: 'Github access token used to checkout the repo'
    required: true
  path:
    description: 'Github access token used to checkout the repo'
    default: .
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: |
        echo "${{ inputs.repos }}" | checkout.sh
      env:
        TOKEN: ${{ inputs.token }}
        TARGET_FOLDER: ${{ inputs.folder }}
      shell: bash
