name: CI
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      uses: ./actions/.github/actions/check-out-many
        with:
          who-to-greet: 'Mona the Octocat'

